/**
 * Order API
 * API documentation for Order API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrderStatus = 'created' | 'confirmed' | 'delivered' | 'canceled';

export const OrderStatus = {
    Created: 'created' as OrderStatus,
    Confirmed: 'confirmed' as OrderStatus,
    Delivered: 'delivered' as OrderStatus,
    Canceled: 'canceled' as OrderStatus
};

