/**
 * Order API
 * API documentation for Order API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';


export interface Order { 
    amount: number;
    username: string;
    status: OrderStatus;
    transactionId: string;
    _id: string;
}

