FROM node:14.17-slim

WORKDIR /app

COPY ./dist/apps/order-api .

ENV ORDER_API_PORT=8877
ENV ORDER_SERVICE_PORT=8876

RUN npm install --production
# dependencies that nestjs needs
RUN npm install tslib @nestjs/platform-socket.io

EXPOSE ${ORDER_API_PORT}
EXPOSE ${ORDER_SERVICE_PORT}

CMD ["node", "./main.js"]
